/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  tutorialSidebar:[
    {
      type: "doc",
      id: "intro"
    },
    {
      type: 'category',
      label: '基本的な操作方法',
      link: {
        type: "doc",
        id: "tutorial/intro",
      },
      items: [
        {
          type: 'doc',
          id: 'tutorial/upload-photo',
        },
        {
          type: 'doc',
          id: 'tutorial/register-person',
        },
        {
          type: 'doc',
          id: 'tutorial/analyze-photos',
        },
        {
          type: 'doc',
          id: 'tutorial/create-album',
        },
      ],
    },
    {
      type: 'link',
      label: 'お問合せ',
      href: 'https://docs.google.com/forms/d/1cNOopskyfno0MVrXyGLwSCociKAzPu1elNI0TBNUucE',
    },
  ],
};

module.exports = sidebars;
